apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Salicaceae/VDT-frontend.git"
    path: argocd
    targetRevision: HEAD
    helm:
      valueFiles:
        - >-
          https://raw.githubusercontent.com/SalicaceaeD/VDT-frontend-config/main/values.yaml
  destination:
    namespace: vdt
    server: "https://kubernetes.default.svc"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true