apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Salicaceae/VDT-frontend.git"
    targetRevision: HEAD
    helm:
      valueFiles:
        - >-
          https://raw.githubusercontent.com/SalicaceaeD/VDT-frontend-config/main/values.yaml
  destination:
    server: "https://192.168.11.101:6443"
    namespace: 