apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/SalicaceaeD/VDT-frontend.git"
    path: argocd
    targetRevision: HEAD
  destination:
    namespace: vdt
    server: "https://192.168.49.3:30706"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true